version: '3.5'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - .:/usr/app/
      - /usr/app/node_modules
    ports:
      - "8080:8080"
    networks:
      - gp_sail
networks:
  gp_sail:
    external: true
